<a href="https://colab.research.google.com/github/Anshika91/Anshi/blob/main/numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

3.Create 1-D Array in numpy: 

In [1]:
import numpy as np
a1 = np.array((1,2,3,4,5))
a1

array([1, 2, 3, 4, 5])

4. Use list to create 1D array (you may also specify data type i.e. dtype=’int16’) 

In [2]:
import numpy as np
a2=np.array([3,4.5,6,1,2.5],dtype='int16')
a2

array([3, 4, 6, 1, 2], dtype=int16)

5.User tuple to create 1D array

In [3]:
import numpy as np
a3=np.array((56,34,12,78))
a3

array([56, 34, 12, 78])

6.Use arange function to create 1D array of int

In [4]:
import numpy as np
a4=np.arange(1,15,3)
a4

array([ 1,  4,  7, 10, 13])

7.a Use arange function to create 1D array of float ( may use dtype = symbols(int->‘i’, uint-
>’u’,float->’f’,double->’d’,complex->’D’,bool->’b’)

In [5]:
import numpy as np
a5=np.arange(1,15,2,dtype='f')
a5

array([ 1.,  3.,  5.,  7.,  9., 11., 13.], dtype=float32)

7.b

In [6]:
import numpy as np
a6=np.arange(1,15,2,dtype='i')
a6

array([ 1,  3,  5,  7,  9, 11, 13], dtype=int32)

7.c

In [7]:
import numpy as np
a7=np.arange(1,15,2,dtype='i')
a7

array([ 1,  3,  5,  7,  9, 11, 13], dtype=int32)

8.  Create 1D array of mixed elements int and float, and print the array and see the output

In [8]:
import numpy as np
a8=np.array((1,2,3.4,8,1.5))
print(a8)

[1.  2.  3.4 8.  1.5]


9.Create 1D array of mixed elements int, float, and str, then print the array and see the output


In [9]:
import numpy as np
a9=np.array((1,2,3.4,'a',1.5,'i'))
print(a9)

['1' '2' '3.4' 'a' '1.5' 'i']


10.Create a 2D array of dimensions 2x2

In [10]:
import numpy as np
m1=np.zeros((2,2),dtype=int)
m1

array([[0, 0],
       [0, 0]])

11.Print the shape, size, and memory used by this array in bytes (use itemsize, or nbytes)

In [11]:
import numpy as np
print(m1.shape)
print(m1.size)
print(m1.size * m1.itemsize)

(2, 2)
4
32


12.Check the type of any array variable

In [12]:
import numpy as np
print(type(m1))

<class 'numpy.ndarray'>


13.Check indexing on array with help of examples

In [13]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr[3])

4


14.Using arange function create an 3D array of dimensions = (2,3,4) , first element of this array
is 0 and last element is 23 in increasing order, store this array in a variable b.

In [14]:
import numpy as np
b=np.arange(0,24,1)
b=b.reshape(2,3,4)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


15.What index can produce output: array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])

In [15]:
import numpy as np
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

16.What index can produce output: 0 

In [16]:
import numpy as np
b[0][0][0]

0

17.What index can produce output: array([4, 5, 6, 7]) 

In [17]:
import numpy as np
b[0][1]

array([4, 5, 6, 7])

18.What index can produce output: array([0,12])

In [19]:
import numpy as np
b[:,0:4:3,0]

array([[ 0],
       [12]])

19.What index can produce output: array([4,6]) 

In [20]:
import numpy as np
b[0,1,0:3:2]

array([4, 6])

20.. Check the output of b[… , 1]

In [21]:
import numpy as np
b[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

21.What index can produce output: array( [1, 5, 9] ) 

In [22]:
import numpy as np
b[0,:,1]

array([1, 5, 9])

22.What index can produce output: array([3,7,11])

In [26]:
import numpy as np
b[0,:,3]

array([ 3,  7, 11])

23.What index can produce output: array([11, 7,3]) 

In [27]:
import numpy as np
b[0,::-1,3]

array([11,  7,  3])

24.What index can produce output: array([3,11])


In [28]:
import numpy as np
b[0,0:3:2,3]

array([ 3, 11])

25.Use function ravel() with array b, and observe the output 

In [29]:
import numpy as np
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

26.Use function flatten() with array b, and observe the output 

In [30]:
import numpy as np
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

27.Use function transpose() with array b, check the output

In [31]:
import numpy as np
b.transpose()

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

28. Use function T() with array b,
check the output

In [32]:
import numpy as np
b.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

29.aUse function concatenate on two arrays with axis 0, and axis 1 and observe the output: i.e
np.concatenate((arr1,arr2),axis=0) & np.concatenate((arr1,arr2),axis=1)

In [33]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[10,11,12],[13,14,15],[16,17,18]])
c=np.concatenate((arr1,arr2),axis=0)
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


29.b

In [34]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[10,11,12],[13,14,15],[16,17,18]])
d=np.concatenate((arr1,arr2),axis=1)
print(d)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


30.Use function astype() to convert the array to an array on another type A=array([[0, 1], [2,
3],[4, 5]]) A.astype(float) or A.astype(‘f’) or A.astype(‘float64’) A.astype(bool)

In [35]:
import numpy as np
A=np.array([[0, 1], [2, 3],[4, 5]])
print(A.astype(float))
print(A.astype(bool))

[[0. 1.]
 [2. 3.]
 [4. 5.]]
[[False  True]
 [ True  True]
 [ True  True]]


31.aCheck the output of “ np.eye(3)” and “np.zeros(3)”

In [36]:
import numpy as np
B=np.eye(3)
print(B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


31.b

In [37]:
import numpy as np
C=np.zeros(3)
print(C)

[0. 0. 0.]


33.Find matrix multiplication user dot function 

In [38]:
import numpy as np
arr1=np.array([[0,1,2],[3,4,5],[6,7,8]])
arr2=np.array([[6,7,8],[3,4,5],[0,1,2]])
ans=np.dot(arr1,arr2)
print(ans)

[[ 3  6  9]
 [30 42 54]
 [57 78 99]]


34.Find element wise multiplication of two matrices using multiply function

In [39]:
import numpy as np
arr1=np.array([[0,1,2],[3,4,5],[6,7,8]])
arr2=np.array([[6,7,8],[3,4,5],[0,1,2]])
ans=np.multiply(arr1,arr2)
print(ans)

[[ 0  7 16]
 [ 9 16 25]
 [ 0  7 16]]


36.. Creating new dtype: record=np.dtype([('name',str,40),('no_of_items',int),('price','float64')]) 

In [40]:
import numpy as np
record=np.dtype([('name',str,40),('no_of_items',int),('price','float64')])
print(np.array([1,3,2,4],dtype=record))

[('1', 1, 1.) ('3', 3, 3.) ('2', 2, 2.) ('4', 4, 4.)]


37.Store record type values in variable items, 

In [41]:
import numpy as np
item=np.array([1,3,2,4],dtype=record)
item

array([('1', 1, 1.), ('3', 3, 3.), ('2', 2, 2.), ('4', 4, 4.)],
      dtype=[('name', '<U40'), ('no_of_items', '<i8'), ('price', '<f8')])

38.items=np.array([('life of dvd',42,30.50),('Butter',10,22.75)], dtype=record)

In [42]:
import numpy as np
items=np.array([('life of dvd',42,30.50),('Butter',10,22.75)], dtype=record)
items

array([('life of dvd', 42, 30.5 ), ('Butter', 10, 22.75)],
      dtype=[('name', '<U40'), ('no_of_items', '<i8'), ('price', '<f8')])

39.Cross Product:

In [43]:
import numpy as np
a=np.array([1,5,3])
a=np.cross(a,a)
a

array([0, 0, 0])

40.* product


In [44]:
import numpy as np
brr=np.array([[1,2,3],[4,5,6],[7,8,9]])
crr=np.array([[0,1,2],[3,4,5],[7,8,9]])
brr*crr

array([[ 0,  2,  6],
       [12, 20, 30],
       [49, 64, 81]])

41.
@ product

In [45]:
import numpy as np
brr=np.array([[1,2,3],[4,5,6],[7,8,9]])
crr=np.array([[0,1,2],[3,4,5],[7,8,9]])
brr@crr

array([[ 27,  33,  39],
       [ 57,  72,  87],
       [ 87, 111, 135]])

32.Find minimum, maximum, and average of an array 

In [46]:
import numpy as np
A=np.array([0,1,2,3,4,5,6,7])
print(A.min())
print(A.max())
print(np.average(A))

0
7
3.5
